#!/bin/bash
# NEXTFLOW TASK: db_search_comet (3)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a ALL_CHILD
    while read P PP;do
        ALL_CHILD[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    walk() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${ALL_CHILD[$1]:=}; do walk $i; done
    }

    walk $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /home/zeth/docker_images/guide_seq_container/work/a7/a75a6514e89f866d3af65403ab039d/.exitcode
  set +u
  [[ "$tee1" ]] && kill $tee1 2>/dev/null
  [[ "$tee2" ]] && kill $tee2 2>/dev/null
  [[ "$ctmp" ]] && rm -rf $ctmp || true
  docker rm $NXF_BOXID &>/dev/null || true
  exit $exit_status
}

on_term() {
    set +e
    docker kill $NXF_BOXID
}

trap on_exit EXIT
trap on_term TERM INT USR1 USR2

export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A)"
NXF_SCRATCH=''
[[ $NXF_DEBUG > 0 ]] && nxf_env
touch /home/zeth/docker_images/guide_seq_container/work/a7/a75a6514e89f866d3af65403ab039d/.command.begin
# task environment
nxf_taskenv() {
cat << EOF
export JOBLIB_TEMP_FOLDER="/tmp"
export PATH="/home/zeth/.nextflow/assets/nf-core/mhcquant/bin:\$PATH"
EOF
}

[[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
# stage input files
rm -f MM15_Melanom_1_B_1.mzML
rm -f test_decoy.fasta
ln -s /home/zeth/docker_images/guide_seq_container/work/a7/a75a6514e89f866d3af65403ab039d/tmp/35/80b8393cc867d08a46ccda8ff4fdd4/MM15_Melanom_1_B_1.mzML MM15_Melanom_1_B_1.mzML
ln -s /home/zeth/docker_images/guide_seq_container/work/03/3992ec1efc0e0bac95c11a97e5d871/test_decoy.fasta test_decoy.fasta

set +e
ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
cout=$ctmp/.command.out; mkfifo $cout
cerr=$ctmp/.command.err; mkfifo $cerr
tee .command.out < $cout &
tee1=$!
tee .command.err < $cerr >&2 &
tee2=$!
(
docker run -i --memory 6144m -e "NXF_DEBUG=${NXF_DEBUG:=0}" -v $(nxf_mktemp):/tmp -v /home/zeth:/home/zeth -v "$PWD":"$PWD" -w "$PWD" --entrypoint /bin/bash --name $NXF_BOXID nfcore/mhcquant:1.2.6 -c "eval $(nxf_taskenv); /bin/bash /home/zeth/docker_images/guide_seq_container/work/a7/a75a6514e89f866d3af65403ab039d/.command.stub"
) >$cout 2>$cerr &
pid=$!
wait $pid || ret=$?
wait $tee1 $tee2
